config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :units, only: [:index, :show] do 
    resources :tests, only: [:index]
    member do
      get :download_resource
    end
  end

  resources :tests, only: [:show] do 
    resources :questions, only: [:index, :show]
    resources :user_tests, only: [:new] do
    end
  end

  root to: 'visitors#index'
end

app/models/cat.rb
#
# This class represents a CAT(Continous accessment Test)
#
class CAT < Test
end

app/models/course.rb
#
# This class represents the course the user is taking
#
class Course < ActiveRecord::Base
  has_many :units
end

app/models/end_of_semester_exam.rb
#
# This class represents End of semester exam
#
class EndOfSemesterExam < Test
end

app/models/lecturer.rb
class Lecturer < User
  has_many :units
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :test
end

app/models/test.rb
#
# This class represents test that belongs to a use
#
class Test < ActiveRecord::Base
  belongs_to :unit
  has_many :questions
  has_many :user_tests

  delegate :code, to: :unit, prefix: true, allow_nil: false
  delegate :name, to: :unit, prefix: true, allow_nil: false

  def has_been_taken?(user)
  	user_test = user.user_tests.find_by(test_id: id)
  	user_test && user_test.status = 'complete'
  end
end

app/models/unit.rb
#
# This class represents a single unit within a course that a user is taking
#
class Unit < ActiveRecord::Base
  belongs_to :course
  has_many :tests

  belongs_to :lecturer, foreign_key: :lecturer_id

  delegate :name, to: :course, prefix: true, allow_nil: false
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :user_tests
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user_test.rb
class UserTest < ActiveRecord::Base
  belongs_to :user
  belongs_to :question
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :find_unit, only: [:index]

  def index
  	@tests = @unit.tests
  end

  def show
    @test = Test.find(params[:id])
  end

  private

  def find_unit
  	@unit = Unit.find(params[:unit_id])
  end
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :find_course

  def index
  	@units = @course.units
  end

  def show
    @unit = Unit.find(params[:id])
  end

  def download_resource
    @unit = Unit.find(params[:id])
    folder = @unit.code = 'SZL 2111' ? 'hiv_aids' : 'communitaction_skills'
    file = "#{Rails.root}/public/reading_materials/#{folder}/lesson_1.txt"
    send_file file, type: 'application/text', x_sendfile: true
  end

  private

  def find_course
  	@course = Course.first
  end 
end

app/controllers/user_tests_controller.rb
class UserTestsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :find_course

  def take
    
  end

  private

  def find_course
  	@course = Course.first
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to :back, :alert => "Access denied."
    end
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Masomo', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<!--<li><%#= link_to 'About', page_path('about') %></li> -->
<% if user_signed_in? %>
  <li><%= link_to 'Units', units_path %></li>
  <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method =>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Masomo" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Masomo" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/units/_unit.html.erb
<td><%= link_to unit.code, unit %></td>
<td><%= link_to unit.name, unit %></td>

app/views/units/index.html.erb
<div class="container">
  <div class="row">
    <h3>Units</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @units.each do |unit| %>
            <tr>
              <%= render unit %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/units/show.html.erb
<h3>Unit</h3>
<div style="padding-top: 20px;">
  <table style="width: 400px;" class="table">
    <tbody>
      <tr>
  	    <td>Code</td>
  	    <td><%= @unit.code %></td>
      </tr> 

      <tr>
  	    <td>Name</td>
  	    <td><%= @unit.name %></td>
      </tr> 

      <tr>
  	    <td>Course</td>
  	    <td><%= @unit.course_name %></td>
      </tr> 

      <tr>
        <td>Leason 1</td>
        <td><%= link_to 'Download', download_resource_unit_path(@unit) %></td>
      </tr> 
    </tbody>
  </table>
</div>

<%= link_to 'View tests', unit_tests_path(@unit) %>

app/views/users/_user.html.erb
<td><%= link_to user.name, user %></td>
<td><%= link_to user.email, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/index.html.erb
<% if user_signed_in? %>
  <h3>Welcome <b><%= current_user.name %></b></h3>
  <p>Your have regitstered for the <%= Course.first.name %> course</p>
<% end %>